/*************** SDCC fucntion address ***************/
#define SDCCMAP_cg_simpleProfileChangeCB                   0x8800
#define SDCCMAP_cg_accelEnablerChangeCB                    0x8832
#define SDCCMAP_cg_battProfileChangeCB                     0x888e
#define SDCCMAP_cg_EVT_1_CB                                0x888f
#define SDCCMAP_cg_EVT_2_CB                                0x88b5
#define SDCCMAP_cg_EVT_3_CB                                0x88d7
#define SDCCMAP_cg_EVT_4_CB                                0x88d8
#define SDCCMAP_cg_timeserviceChangeCB                     0x88d9
#define SDCCMAP_rtcInit                                    0x8a49
#define SDCCMAP_rtcSetTime                                 0x8a4d
#define SDCCMAP_rtcGetTime                                 0x8a69
#define SDCCMAP_rtcSetDate                                 0x8aa8
#define SDCCMAP_rtcGetDate                                 0x8ac8
#define SDCCMAP_rtcGetAlarm                                0x8b0c
#define SDCCMAP_rtcSetAlarm                                0x8b50
#define SDCCMAP_Accel_AddService                           0x8b90
#define SDCCMAP_Accel_RegisterAppCBs                       0x8b9d
#define SDCCMAP_Accel_SetParameter                         0x8ba7
#define SDCCMAP_Accel_GetParameter                         0x8bc7
#define SDCCMAP_osalTimerInit                              0x8be5
#define SDCCMAP_osal_start_timerEx                         0x8be9
#define SDCCMAP_osal_start_reload_timer                    0x8c2f
#define SDCCMAP_osal_stop_timerEx                          0x8c75
#define SDCCMAP_osal_get_timeoutEx                         0x8c93
#define SDCCMAP_osal_timer_ISR                             0x8cb6
#define SDCCMAP_osal_adjust_timers                         0x8cb7
#define SDCCMAP_osalTimerUpdate                            0x8cb8
#define SDCCMAP_osal_timer_num_active                      0x8cc3
#define SDCCMAP_osal_sleep_timers                          0x8cc4
#define SDCCMAP_osal_unsleep_timers                        0x8cc5
#define SDCCMAP_osal_GetSystemClock                        0x8cc6
#define SDCCMAP_osal_next_timeout                          0x8cd1
#define SDCCMAP_accInit                                    0x8cd2
#define SDCCMAP_accWriteReg                                0x8cd6
#define SDCCMAP_accReadReg                                 0x8cea
#define SDCCMAP_accReadMultiReg                            0x8d06
#define SDCCMAP_accReadAcc                                 0x8d0e
#define SDCCMAP_accReadAllAcc                              0x8d4d
#define SDCCMAP_accSetFreeFallEvent                        0x8d4e
#define SDCCMAP_timeservice_AddService                     0x8d52
#define SDCCMAP_timeservice_RegisterAppCBs                 0x8d5f
#define SDCCMAP_timeservice_SetParameter                   0x8d69
#define SDCCMAP_timeservice_GetParameter                   0x8d89
#define SDCCMAP_SimpleProfile_AddService                   0x8da7
#define SDCCMAP_SimpleProfile_RegisterAppCBs               0x8db4
#define SDCCMAP_SimpleProfile_SetParameter                 0x8dbe
#define SDCCMAP_SimpleProfile_GetParameter                 0x8dde
